# Generated by Django 4.1.5 on 2023-02-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatito',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Gato', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
