# Generated by Django 4.1.5 on 2023-02-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatito',
            old_name='Id',
            new_name='id',
        ),
    ]
